"""empty message

Revision ID: d4c45add7d3c
Revises: 48e5b14102f2
Create Date: 2024-07-25 11:43:34.142729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4c45add7d3c'
down_revision = '48e5b14102f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_availabilities', schema=None) as batch_op:
        batch_op.alter_column('availability_slot_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('availability_slot_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_availabilities', schema=None) as batch_op:
        batch_op.alter_column('availability_slot_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('availability_slot_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
